more_topics_button_text:
  type: string
  default: "More"
  description: "Text displayed on More button"
post_button_text:
  type: string
  default: "Post"
  description: "Text displayed on Post button"
feed_list:
  placeholder: "Title, List length, Filter, Tag, Category id, Link"
  client: true
  default: "Latest Topics, 3, latest, , , /latest| Top Topics, 3, top, , , /top| Lounge, 3, latest, , 4, /c/lounge/4| Featured Tag,3,latest,featured,,/tag/featured"
  type: list
  description: |
    Each line should be in the format of <code>Feed title</code>, <code>List length</code>, <code>List filter</code>, <code>Tag filter</code>, <code>Category filter</code>, <code>Feed link</code>.
plugin_outlet:
  type: enum
  default: "above-main-container"
  choices:
    - "above-main-container"
    - "below-site-header"
    - "discovery-list-container-top"
  description: "Advanced layout setting"
